spring:
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
  application:
    name: Top Wine Assistant
  profiles:
    default:
      dev
  jooq:
    sql-dialect: postgres
ai:
  provider: ollama
  base-url: http://localhost:11434/v1
  model: qwen3:8b
  api-key: ""
  timeout-seconds: 20
  max-tokens: 768
  temperature: 0.6

logging:
  level:
    ru.topwine.assistant: INFO
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG
