name: CI

on:
  push:
    branches: [ main, master, develop, 'feature/**' ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # ---- FIX gradlew on Linux runners ----
      - name: Normalize gradlew line endings & make executable
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      # (optional) light wrapper check; skip if flaky
      - name: Gradle version
        run: ./gradlew --version

      - name: Build & test
        run: ./gradlew --no-daemon clean test build

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
