name: CI

on:
  push:
    branches: [ main, master, develop, 'feature/**' ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch: { }

env:
  SPRING_PROFILES_ACTIVE: dev
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: topwine
  DB_USER: topwine
  DB_PASSWORD: topwine

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: topwine
          POSTGRES_USER: topwine
          POSTGRES_PASSWORD: topwine
        options: >-
          --health-cmd="pg_isready -U topwine -d topwine"
          --health-interval=5s --health-timeout=3s --health-retries=5
        # no "ports" needed when using service DNS name

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Normalize gradlew line endings & make executable
        run: |
          sed -i 's/\r$//' gradlew
          chmod +x gradlew

      - name: Gradle version
        run: ./gradlew --version

      - name: Build & test
        run: ./gradlew --no-daemon clean test build

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
